### ISSUE TITLE
Create trip supplies checklist

### ISSUE THREAD

**Issue by ianprime0509** [wayfinder-project/wayfinder#13]
**User story**
As a logged-in user in the trip planning view, I can create a checklist of important trip supplies (e.g. phone charger, spare tire, etc.).

**Comment by ianprime0509** [comment]
The back-end component of this story was merged in #104.

**Comment by ianprime0509** [comment]
The front-end component was merged in #112, but work is still being done to style it and integrate it into the trip view.

**Comment by LoganSmithDarkLight** [comment]
Added list of items which can be checked off or deleted.
